openapi: 3.0.0
info:
  title: Video Game Library API
  description: API for managing a library of video games
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /games:
    get:
      summary: Retrieve all video games
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
    post:
      summary: Add a new video game
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /games/{id}:
    get:
      summary: Retrieve a specific video game by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the video game to retrieve
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
    put:
      summary: Update a specific video game by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the video game to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      summary: Delete a specific video game by ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the video game to delete
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        gameStudio:
          type: string
        ageRating:
          type: string
        numberOfPlayers:
          type: integer
        genre:
          type: string
      required:
        - title
        - gameStudio
        - ageRating
        - numberOfPlayers
        - genre
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
